// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: Service_proto/AAA.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Username struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Username) Reset() {
	*x = Username{}
	mi := &file_Service_proto_AAA_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Username) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Username) ProtoMessage() {}

func (x *Username) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_AAA_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Username.ProtoReflect.Descriptor instead.
func (*Username) Descriptor() ([]byte, []int) {
	return file_Service_proto_AAA_proto_rawDescGZIP(), []int{0}
}

func (x *Username) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Username) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type JWT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JWT           string                 `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWT) Reset() {
	*x = JWT{}
	mi := &file_Service_proto_AAA_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWT) ProtoMessage() {}

func (x *JWT) ProtoReflect() protoreflect.Message {
	mi := &file_Service_proto_AAA_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWT.ProtoReflect.Descriptor instead.
func (*JWT) Descriptor() ([]byte, []int) {
	return file_Service_proto_AAA_proto_rawDescGZIP(), []int{1}
}

func (x *JWT) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

var File_Service_proto_AAA_proto protoreflect.FileDescriptor

const file_Service_proto_AAA_proto_rawDesc = "" +
	"\n" +
	"\x17Service_proto/AAA.proto\x12\x04netV\"2\n" +
	"\bUsername\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x17\n" +
	"\x03JWT\x12\x10\n" +
	"\x03JWT\x18\x01 \x01(\tR\x03JWT2Z\n" +
	"\x03AAA\x12(\n" +
	"\vCreateToken\x12\x0e.netV.Username\x1a\t.netV.JWT\x12)\n" +
	"\fExtractToken\x12\t.netV.JWT\x1a\x0e.netV.UsernameB\x16Z\x14netVServer/AAA/pb;pbb\x06proto3"

var (
	file_Service_proto_AAA_proto_rawDescOnce sync.Once
	file_Service_proto_AAA_proto_rawDescData []byte
)

func file_Service_proto_AAA_proto_rawDescGZIP() []byte {
	file_Service_proto_AAA_proto_rawDescOnce.Do(func() {
		file_Service_proto_AAA_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Service_proto_AAA_proto_rawDesc), len(file_Service_proto_AAA_proto_rawDesc)))
	})
	return file_Service_proto_AAA_proto_rawDescData
}

var file_Service_proto_AAA_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Service_proto_AAA_proto_goTypes = []any{
	(*Username)(nil), // 0: netV.Username
	(*JWT)(nil),      // 1: netV.JWT
}
var file_Service_proto_AAA_proto_depIdxs = []int32{
	0, // 0: netV.AAA.CreateToken:input_type -> netV.Username
	1, // 1: netV.AAA.ExtractToken:input_type -> netV.JWT
	1, // 2: netV.AAA.CreateToken:output_type -> netV.JWT
	0, // 3: netV.AAA.ExtractToken:output_type -> netV.Username
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Service_proto_AAA_proto_init() }
func file_Service_proto_AAA_proto_init() {
	if File_Service_proto_AAA_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Service_proto_AAA_proto_rawDesc), len(file_Service_proto_AAA_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Service_proto_AAA_proto_goTypes,
		DependencyIndexes: file_Service_proto_AAA_proto_depIdxs,
		MessageInfos:      file_Service_proto_AAA_proto_msgTypes,
	}.Build()
	File_Service_proto_AAA_proto = out.File
	file_Service_proto_AAA_proto_goTypes = nil
	file_Service_proto_AAA_proto_depIdxs = nil
}
