// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: Service_proto/AAA.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AAA_CreateToken_FullMethodName = "/netV.AAA/CreateToken"
)

// AAAClient is the client API for AAA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AAAClient interface {
	CreateToken(ctx context.Context, in *Username, opts ...grpc.CallOption) (*JWT, error)
}

type aAAClient struct {
	cc grpc.ClientConnInterface
}

func NewAAAClient(cc grpc.ClientConnInterface) AAAClient {
	return &aAAClient{cc}
}

func (c *aAAClient) CreateToken(ctx context.Context, in *Username, opts ...grpc.CallOption) (*JWT, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JWT)
	err := c.cc.Invoke(ctx, AAA_CreateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AAAServer is the server API for AAA service.
// All implementations must embed UnimplementedAAAServer
// for forward compatibility.
type AAAServer interface {
	CreateToken(context.Context, *Username) (*JWT, error)
	mustEmbedUnimplementedAAAServer()
}

// UnimplementedAAAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAAAServer struct{}

func (UnimplementedAAAServer) CreateToken(context.Context, *Username) (*JWT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}
func (UnimplementedAAAServer) mustEmbedUnimplementedAAAServer() {}
func (UnimplementedAAAServer) testEmbeddedByValue()             {}

// UnsafeAAAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AAAServer will
// result in compilation errors.
type UnsafeAAAServer interface {
	mustEmbedUnimplementedAAAServer()
}

func RegisterAAAServer(s grpc.ServiceRegistrar, srv AAAServer) {
	// If the following call pancis, it indicates UnimplementedAAAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AAA_ServiceDesc, srv)
}

func _AAA_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Username)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_CreateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).CreateToken(ctx, req.(*Username))
	}
	return interceptor(ctx, in, info, handler)
}

// AAA_ServiceDesc is the grpc.ServiceDesc for AAA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AAA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netV.AAA",
	HandlerType: (*AAAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToken",
			Handler:    _AAA_CreateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Service_proto/AAA.proto",
}
